pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success=commitlint
      - check-success=docs
      - check-success=integration
      - check-success=lint
      - check-success=unit
    actions:
      merge:
        method: squash
